error CustomError {
  value: uint
}

fn throwCustomError(value: uint)

fn identity(value: int): int
fn sum(a: int, b: int): int
